'use client'

import React, { useState } from 'react'
import Link from 'next/link'
import { 
  Map, 
  BookOpen, 
  Award, 
  ArrowRight, 
  BrainCircuit, 
  Sliders, 
  FileText, 
  Layers, 
  HelpCircle, 
  Check, 
  Flame, 
  Grid 
} from 'lucide-react'
import { ThemeToggle } from '@/components/ui/ThemeToggle'
import { Logo } from '@/components/ui/Logo'
import { Spark } from '@/components/mascot/Spark'
import { WhyCognara } from '@/components/marketing/WhyCognara'

export default function MarketingPage() {
  // Mascot & Simulator State
  const [sparkEmotion, setSparkEmotion] = useState<'wave' | 'happy' | 'celebrate' | 'thinking' | 'idle'>('wave')
  const [activeSubject, setActiveSubject] = useState<'tech' | 'business' | 'creative'>('tech')
  const [activeDepth, setActiveDepth] = useState<number>(3)

  // FAQ states
  const [openFaq, setOpenFaq] = useState<number | null>(null)

  const depthLabels = ["", "Like I'm 10", "Beginner", "Intermediate", "Advanced", "Expert"]
  
  const subjects = [
    { id: 'tech', label: 'Tech & Code', concept: 'JavaScript Closures' },
    { id: 'business', label: 'Business & Marketing', concept: 'Customer Acquisition Cost (CAC)' },
    { id: 'creative', label: 'Creative Arts', concept: 'Color Theory in Design' }
  ] as const

  const explanations = {
    tech: [
      "",
      "Think of a closure like a magic backpack that a function carries around. Whenever the function is born, it packs all the variables from the room it was created in. Even if the function travels to a completely new place, it can unzip its backpack and grab those variables anytime!",
      "In JavaScript, a closure is a feature where a nested inner function retains access to the variables of its parent function, even after the parent function has finished running. It's like a function remembering its home town.",
      "A closure is the combination of a function bundled together with references to its surrounding state (the lexical environment). Lexical scoping determines variable access based on the physical location of declarations in the source code.",
      "Closures are heap-allocated variable environments captured during lexical parsing. When a parent context is popped off the execution stack, its activation record references are preserved in memory because the returned inner function maintains an active scope chain pointer to them.",
      "At the compiler layer (V8/SpiderMonkey), closures bypass stack allocation. The parser scans for context escaping; if a nested function references an outer binding, V8 allocates that binding in a Heap Context object rather than the Stack. The closure holds a [[Scope]] property reference, preventing GC sweep passes."
    ],
    business: [
      "",
      "Think of CAC like buying tickets to invite friends to a birthday party. If you spend $10 on party invitations and 5 friends show up, inviting each friend cost you $2! That is what CAC is—how much money you spend to get one new customer.",
      "In business, Customer Acquisition Cost (CAC) is the total amount of money a company spends to win a new customer. This includes marketing fees, sales salaries, and ads, divided by the number of customers gained.",
      "Customer Acquisition Cost (CAC) measures the efficiency of sales and marketing operations. It is computed by dividing total acquisition expenses (marketing spend, sales overhead, salaries) by the total number of acquired customers over a specific period.",
      "CAC is a critical unit economics efficiency metric. To evaluate enterprise viability, CAC must be analyzed in relation to LTV (Customer Lifetime Value) using the LTV:CAC ratio. An optimal ratio is 3:1, indicating that the gross margin generated by a customer is triple the cost to acquire them, factoring in payback periods.",
      "Analytically, CAC optimization requires dissecting marginal acquisition cost curves across paid channels. CAC is modeled as: CAC = (Total Marketing Spend + Total Sales Overheads + Customer Success Onboarding Cost) / Total Gained Customers. Dynamic cohort analysis must adjust CAC based on organic virality loops (K-factor) and churn decay coefficients."
    ],
    creative: [
      "",
      "Colors are like friends—some look super happy together, and some fight! Color Theory is a set of secret rules that artists use to mix colors so they look beautiful on your eyes. It is like matching clothes for a party!",
      "Color Theory is a set of practical guidelines for mixing colors and creating visual combinations. It uses the Color Wheel to show how primary colors (red, blue, yellow) combine to create secondary and tertiary tones that feel good to look at.",
      "Color Theory comprises the principles governing color mixing and the visual effects of specific color combinations. Underpinned by the color wheel, designers utilize contrast schemes (analogous, complementary, triadic) to create visual harmony and manage visual weight in compositions.",
      "Color Theory maps color physics and psychological perception. It defines color spaces using Hue, Saturation, and Value (HSV). Designers exploit complementary contrasts to stimulate photoreceptor cells (rods and cones) in the retina, using contrasting temperatures (warm vs cool) to establish visual hierarchy.",
      "At the intersection of optics and human perception, Color Theory is governed by additive (RGB) and subtractive (CMYK) color mixing systems. Chromatic relationships are mapped onto the CIE 1931 color space chromaticity diagram, where relative luminance contrast ratios and simultaneous contrast effects are calculated to ensure accessible visual designs."
    ]
  }

  const faqs = [
    {
      q: "Can I use Cognara to learn non-technical subjects?",
      a: "Yes! Cognara is designed to master any structured body of knowledge. Whether you are studying corporate finance, learning classical guitar, or practicing public speaking, our AI partitions the concepts, creates custom roadmaps, and adjusts explanations to your level."
    },
    {
      q: "How does Cognara know which depth level is right for me?",
      a: "During onboarding, you choose a preferred depth level. You can also change this at any time in your Settings or directly in the header of any active lesson. If a concept feels too complex or too basic, just toggle the depth to reload it immediately."
    },
    {
      q: "Does Cognara query the AI every time I load a page?",
      a: "No. Cognara uses a smart lazy-generation caching layer. The very first time you click a lesson on your roadmap, the AI compiles and structures it for your chosen depth. Once generated, it is cached in our secure database forever. This gives you instant loading times for future visits."
    },
    {
      q: "How are the daily streaks calculated?",
      a: "Your streak increases every calendar day you complete a quiz with a passing score of 60% or higher. Taking multiple quizzes on the same day maintains your streak but does not double-increment it, encouraging consistent, daily habits."
    }
  ]

  return (
    <div className="min-h-screen bg-bg text-text-1 flex flex-col relative overflow-hidden transition-colors duration-200 pb-16">
      {/* Background radial glows */}
      <div className="absolute top-[-20%] left-[-10%] w-[600px] h-[600px] rounded-full bg-gradient-to-br from-primary/10 to-accent/15 blur-[120px] pointer-events-none opacity-60 animate-learning-pulse" />
      <div className="absolute bottom-[-10%] right-[-5%] w-[500px] h-[500px] rounded-full bg-gradient-to-tr from-accent/10 to-primary/15 blur-[100px] pointer-events-none opacity-50" />

      {/* 1. Header Navigation */}
      <header className="relative z-10 max-w-7xl w-full mx-auto px-6 h-20 flex items-center justify-between border-b border-border/40 bg-bg/50 backdrop-blur-md sticky top-0">
        <div className="flex items-center space-x-2 text-primary">
          <Logo className="h-6 w-6" />
          <span className="font-heading text-xl font-bold tracking-tight text-text-1">Cognara</span>
        </div>

        <nav className="flex items-center space-x-6">
          <Link href="/login" className="text-xs text-text-2 hover:text-text-1 font-semibold uppercase tracking-wider transition-colors duration-150">
            Sign In
          </Link>
          <Link 
            href="/signup" 
            className="h-9 px-4 inline-flex items-center justify-center rounded-md font-semibold text-xs uppercase tracking-wider bg-primary hover:bg-primary-hover text-white transition-colors shadow-[0_0_12px_rgba(91,142,255,0.2)]"
          >
            Sign Up
          </Link>
          <ThemeToggle />
        </nav>
      </header>

      {/* 2. Main content container */}
      <main className="relative z-10 max-w-6xl w-full mx-auto px-6 space-y-24 mt-12 md:mt-20">
        
        {/* HERO SECTION */}
        <section className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-center">
          <div className="lg:col-span-7 space-y-6 text-left">
            <span className="inline-flex items-center px-3 py-1 border border-accent/20 bg-accent/5 text-accent text-xs font-mono font-bold uppercase tracking-widest rounded-full">
              Your mind. Your path. Your era.
            </span>
            <h1 className="font-heading text-4xl sm:text-5xl md:text-6xl font-extrabold text-text-1 tracking-tight leading-[1.05]">
              Master Anything. <br />
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-primary to-accent">Calibrated to You.</span>
            </h1>
            <p className="text-text-2 text-sm sm:text-base leading-relaxed max-w-xl">
              Cognara is an AI Learning Operating System. We dynamically compile your learning goals into logical roadmaps, rendering rich lesson layouts and adaptive quiz challenges engineered around your personal schedule and explanation depth.
            </p>

            <div className="flex flex-col sm:flex-row items-center gap-4 pt-4">
              <Link 
                href="/signup"
                className="w-full sm:w-auto h-12 px-8 inline-flex items-center justify-center rounded-lg font-bold text-sm bg-primary hover:bg-primary-hover text-white shadow-[0_0_20px_rgba(91,142,255,0.3)] transition-all duration-150 hover:-translate-y-0.5"
              >
                <span>Start Learning Free</span>
                <ArrowRight className="ml-2 h-4 w-4" strokeWidth={2.5} />
              </Link>
              <Link 
                href="/login"
                className="w-full sm:w-auto h-12 px-8 inline-flex items-center justify-center rounded-lg font-bold text-sm border border-border bg-surface hover:bg-surface-alt text-text-1 transition-all duration-150"
              >
                Sign In to Dashboard
              </Link>
            </div>
          </div>

          {/* Hero Visual Card (Visual Showcase Mockup) */}
          <div className="lg:col-span-5 relative">
            <div className="absolute inset-0 bg-gradient-to-r from-primary/10 to-accent/10 rounded-[12px] blur-xl pointer-events-none" />
            <div className="relative bg-surface border border-border rounded-[12px] p-5 shadow-lg space-y-4">
              <div className="flex items-center justify-between border-b border-border pb-3">
                <div className="flex items-center space-x-1.5">
                  <span className="w-3 h-3 rounded-full bg-error" />
                  <span className="w-3 h-3 rounded-full bg-accent-warm" />
                  <span className="w-3 h-3 rounded-full bg-success" />
                </div>
                <span className="text-[9px] font-mono text-text-3">ROADMAP CONFIGURATION</span>
              </div>
              <div className="space-y-3">
                <div className="flex items-center justify-between">
                  <span className="text-xs text-text-2">Target Goal</span>
                  <span className="text-xs text-text-1 font-semibold">Business Finance & Strategy</span>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-xs text-text-2">Study Schedule</span>
                  <span className="text-xs text-text-1 font-semibold">30 minutes / day</span>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-xs text-text-2">Subject Area</span>
                  <span className="text-xs text-text-1 font-semibold">Corporate Economics</span>
                </div>
              </div>
              <div className="p-3 bg-surface-alt border border-border/60 rounded-[8px] space-y-2">
                <div className="flex items-center justify-between">
                  <span className="text-[10px] font-mono text-accent font-bold">COMPILING CURRICULUM</span>
                  <span className="text-[10px] font-mono text-text-3">100%</span>
                </div>
                <div className="w-full bg-border h-1.5 rounded-full overflow-hidden">
                  <div className="bg-primary h-full w-full rounded-full" />
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* 3-STEP WALKTHROUGH SECTION */}
        <section className="space-y-12">
          <div className="text-center space-y-3">
            <span className="text-xs font-mono uppercase text-primary font-bold tracking-wider">How it works</span>
            <h2 className="font-heading text-3xl font-extrabold text-text-1">A Blueprint Designed For Your Mind</h2>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="p-6 bg-surface border border-border rounded-[10px] space-y-4 shadow-sm flex flex-col justify-between">
              <div className="space-y-3">
                <div className="w-10 h-10 rounded-md bg-primary/10 text-primary flex items-center justify-center border border-primary/15 font-heading font-bold text-base">
                  01
                </div>
                <h3 className="font-heading text-lg font-bold text-text-1">State Your Aspirations</h3>
                <p className="text-text-2 text-xs leading-relaxed">
                  Enter any skill, domain, or subject you wish to master—from software engineering and marketing curves to culinary arts or language practice.
                </p>
              </div>
            </div>

            <div className="p-6 bg-surface border border-border rounded-[10px] space-y-4 shadow-sm flex flex-col justify-between">
              <div className="space-y-3">
                <div className="w-10 h-10 rounded-md bg-accent/10 text-accent flex items-center justify-center border border-accent/15 font-heading font-bold text-base">
                  02
                </div>
                <h3 className="font-heading text-lg font-bold text-text-1">Dynamic Roadmap Partitioning</h3>
                <p className="text-text-2 text-xs leading-relaxed">
                  Our compiler constructs a logical track of modules and milestones, creating lazy-generation lesson stubs ready for your studies.
                </p>
              </div>
            </div>

            <div className="p-6 bg-surface border border-border rounded-[10px] space-y-4 shadow-sm flex flex-col justify-between">
              <div className="space-y-3">
                <div className="w-10 h-10 rounded-md bg-success/10 text-success flex items-center justify-center border border-success/15 font-heading font-bold text-base">
                  03
                </div>
                <h3 className="font-heading text-lg font-bold text-text-1">Adaptive Depth Loading</h3>
                <p className="text-text-2 text-xs leading-relaxed">
                  Open any lesson stub. Toggle explanation layers from simplified analogies to heap memory compiler logic instantly.
                </p>
              </div>
            </div>
          </div>
        </section>

        {/* INTERACTIVE DEMONSTRATOR: ADAPTIVE DEPTH SIMULATOR */}
        <section className="bg-surface border border-border rounded-[12px] p-6 md:p-8 space-y-8 shadow-md relative overflow-hidden">
          <div className="absolute right-0 top-0 w-36 h-36 rounded-full bg-primary/5 blur-2xl pointer-events-none" />
          
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-center">
            <div className="lg:col-span-5 space-y-4">
              <div className="inline-flex items-center space-x-1.5 text-accent font-mono text-xs uppercase tracking-wider font-bold">
                <Sliders className="h-4 w-4" />
                <span>Feature Showcase</span>
              </div>
              <h3 className="font-heading text-2xl font-bold tracking-tight text-text-1 leading-tight">
                Adaptive Explanation Depth
              </h3>
              <p className="text-text-2 text-xs leading-relaxed">
                Watch how Cognara re-structures explanations across 5 distinct cognitive levels. Select a domain tab and click on the depths to see the explanation transform.
              </p>
              
              {/* Category tabs */}
              <div className="flex flex-col space-y-2 pt-2">
                <span className="text-[10px] font-mono text-text-3 uppercase tracking-wider">Select Domain</span>
                <div className="flex flex-col sm:flex-row gap-2">
                  {subjects.map((sub) => (
                    <button
                      key={sub.id}
                      onClick={() => {
                        setActiveSubject(sub.id)
                        setActiveDepth(3) // reset depth to intermediate
                      }}
                      type="button"
                      className={`px-3 py-2 text-left rounded-md border text-xs font-semibold transition-all cursor-pointer ${
                        activeSubject === sub.id
                          ? 'border-primary bg-primary/5 text-primary'
                          : 'border-border bg-surface-alt text-text-2 hover:text-text-1'
                      }`}
                    >
                      {sub.label}
                    </button>
                  ))}
                </div>
              </div>
            </div>

            {/* Simulated UI window */}
            <div className="lg:col-span-7 space-y-4">
              {/* Depth Toggles Header */}
              <div className="flex flex-wrap gap-2 border-b border-border pb-3 justify-start">
                {[1, 2, 3, 4, 5].map((lvl) => (
                  <button
                    key={lvl}
                    onClick={() => setActiveDepth(lvl)}
                    type="button"
                    className={`px-3 py-1.5 rounded-sm font-mono text-[10px] uppercase font-bold tracking-wide transition-all cursor-pointer ${
                      activeDepth === lvl
                        ? 'bg-primary text-white shadow-[0_0_12px_rgba(91,142,255,0.25)]'
                        : 'bg-surface-alt border border-border text-text-2 hover:text-text-1'
                    }`}
                  >
                    <span>Lvl {lvl}</span>
                  </button>
                ))}
              </div>

              {/* Display Box */}
              <div className="p-5 bg-surface-alt border border-border/80 rounded-[8px] space-y-3 min-h-[160px] flex flex-col justify-between relative border-l-2 border-l-accent">
                {/* AI generated badge inside simulator */}
                <div className="absolute right-4 top-4 opacity-75">
                  <span className="inline-flex items-center px-1.5 py-0.5 border border-accent/20 bg-accent/5 text-accent text-[8px] font-mono font-bold uppercase rounded-sm">
                    GENERATED — Lvl {activeDepth} ({depthLabels[activeDepth]})
                  </span>
                </div>
                
                <h4 className="font-heading text-sm font-bold text-text-1 mt-2">
                  Concept: {subjects.find(s => s.id === activeSubject)?.concept}
                </h4>
                <p className="text-text-2 text-xs leading-relaxed whitespace-pre-line pr-2 flex-1">
                  {explanations[activeSubject][activeDepth]}
                </p>
              </div>
            </div>
          </div>
        </section>

        {/* RICH CONTENT SYSTEM PREVIEW */}
        <section className="grid grid-cols-1 lg:grid-cols-2 gap-8 items-center">
          <div className="space-y-6">
            <span className="text-xs font-mono uppercase text-primary font-bold tracking-wider">Rich Layout Engine</span>
            <h3 className="font-heading text-3xl font-extrabold text-text-1 leading-tight">
              Lessons Must Not Be Walls of Text.
            </h3>
            <p className="text-text-2 text-xs sm:text-sm leading-relaxed">
              Every concept requires the correct pedagogical representation. Cognara's layout engine dynamically injects custom structural blocks to ensure concepts click immediately:
            </p>

            <ul className="space-y-3">
              {[
                { title: "Monaco Code Practice Playgrounds", desc: "Live code editor with syntax highlighting for hands-on technical lessons (HTML/CSS/JS)." },
                { title: "AI Soft-Skills Writing Workspaces", desc: "Advanced text area with instant, context-aware AI feedback for paragraph assignments." },
                { title: "Actionable Task Checklists", desc: "Visual, step-by-step guides for practical offline training exercises." },
                { title: "Interactive Spark Mascot Greetings", desc: "A CSS/SVG animated AI companion that celebrates your study wins and habit streaks." },
                { title: "Progressive Subscription Paywalls", desc: "Freemium plan layout options and structured limits tailored for active goals." },
                { title: "Colored Context Callouts", desc: "Important, Warning, Tip, and Pro Tip callouts highlighting critical concepts." }
              ].map((item, idx) => (
                <li key={idx} className="flex items-start text-xs text-text-2">
                  <Check className="h-4 w-4 text-success mr-2.5 flex-shrink-0 mt-0.5" strokeWidth={3} />
                  <div>
                    <span className="font-bold text-text-1">{item.title}</span> — {item.desc}
                  </div>
                </li>
              ))}
            </ul>
          </div>

          {/* Graphical representation grid */}
          <div className="grid grid-cols-2 gap-4">
            <div className="p-4 bg-surface border border-border rounded-[10px] space-y-2 shadow-sm">
              <span className="text-[8px] font-mono text-accent">TIP CALLOUT</span>
              <div className="text-xs font-bold text-text-1">💡 Focus on Payback Periods</div>
              <p className="text-[10px] text-text-2 leading-relaxed">When analyzing CAC, prioritize payback periods. A low CAC is risky if payback takes over 12 months.</p>
            </div>

            <div className="p-4 bg-surface border border-border rounded-[10px] space-y-3 shadow-sm">
              <span className="text-[8px] font-mono text-accent">DIAGRAM BLOCK</span>
              <pre className="text-[9px] font-mono text-text-2 leading-tight">
{`[Target Audience]
   └── conversion 
         └── [Acquired User]`}</pre>
            </div>

            <div className="p-4 bg-surface border border-border rounded-[10px] space-y-2 shadow-sm col-span-2">
              <span className="text-[8px] font-mono text-accent">COMPARISON TABLE</span>
              <div className="grid grid-cols-2 gap-2 text-[9px] font-mono">
                <div className="p-2 bg-error/5 border border-error/15 text-error rounded-sm">❌ High CAC (Sales heavy)</div>
                <div className="p-2 bg-success/5 border border-success/15 text-success rounded-sm">✅ Low CAC (Word of Mouth)</div>
              </div>
            </div>
          </div>
        </section>

        {/* PROGRESS & COACH WIDGET SHOWCASE */}
        <section className="bg-surface border border-border rounded-[12px] p-6 md:p-8 space-y-8 shadow-md">
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-center">
            
            {/* Visual Dashboard Card Mockup */}
            <div className="lg:col-span-6 space-y-4 order-last lg:order-first">
              <div className="p-5 bg-surface-alt border border-border/80 rounded-[8px] space-y-4">
                <div className="flex items-center justify-between border-b border-border pb-3">
                  <div className="flex items-center space-x-2">
                    <Flame className="h-4 w-4 text-accent-warm fill-current" />
                    <span className="text-[10px] font-mono text-text-1 font-bold">12-DAY STUDY STREAK</span>
                  </div>
                  <span className="text-[9px] font-mono text-text-3">ANALYTICS ENGINE</span>
                </div>
                {/* Visual Heatmap Mock */}
                <div className="space-y-2">
                  <div className="text-[8px] font-mono text-text-3 uppercase">Activity Calendar</div>
                  <div className="flex gap-1">
                    {[1, 2, 0, 3, 1, 0, 2, 3, 3, 1, 2, 0, 1, 3, 2, 0, 1].map((val, i) => {
                      let color = 'bg-border/40'
                      if (val === 1) color = 'bg-primary/25'
                      if (val === 2) color = 'bg-primary/50'
                      if (val === 3) color = 'bg-primary'
                      return <div key={i} className={`w-3.5 h-3.5 rounded-sm ${color}`} />
                    })}
                  </div>
                </div>
                {/* AI Coach card Mock */}
                <div className="border-l-[3px] border-accent bg-accent/5 p-3.5 rounded-r-[8px] space-y-1">
                  <span className="text-[8px] font-mono text-accent font-bold uppercase tracking-wider">AI Coach Insight</span>
                  <p className="text-[10px] text-text-1 leading-normal">
                    You're doing great! Your quiz accuracy trajectory is at 88%. You mastered Customer Acquisition Cost calculations today. Continue to LTV ratios tomorrow.
                  </p>
                </div>
              </div>
            </div>

            <div className="lg:col-span-6 space-y-6">
              <span className="text-xs font-mono uppercase text-primary font-bold tracking-wider">Analytics & Coach</span>
              <h3 className="font-heading text-3xl font-extrabold text-text-1 leading-tight">
                Streaks, Heatmaps, and Personalized Insights.
              </h3>
              <p className="text-text-2 text-xs sm:text-sm leading-relaxed">
                Stay motivated with interactive vitals metrics. Cognara logs your daily studies and quiz scores, generating a GitHub-style activity heatmap, score charts, and direct coach feedback to highlight strengths and recommend reviews.
              </p>
            </div>
          </div>
        </section>

        {/* INTERACTIVE MASCOT SHOWCASE */}
        <section className="bg-surface border border-border rounded-[12px] p-6 md:p-8 space-y-8 shadow-md relative overflow-hidden">
          <div className="absolute left-0 top-0 w-36 h-36 rounded-full bg-accent/5 blur-2xl pointer-events-none" />
          
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-center">
            
            {/* Spark mascot column */}
            <div className="lg:col-span-5 flex flex-col items-center justify-center p-6 bg-surface-alt border border-border/60 rounded-[8px] min-h-[300px] relative">
              <div className="mb-6 flex justify-center items-center w-full">
                <Spark emotion={sparkEmotion} size={120} />
              </div>
              
              <div className="w-full space-y-3">
                <span className="text-[10px] font-mono text-text-3 uppercase tracking-wider block text-center">Tap to Change Spark's Emotion</span>
                <div className="flex flex-wrap gap-2 justify-center">
                  {(['wave', 'happy', 'celebrate', 'thinking', 'idle'] as const).map((emotion) => (
                    <button
                      key={emotion}
                      onClick={() => setSparkEmotion(emotion)}
                      type="button"
                      className={`px-2.5 py-1 rounded-md text-[10px] font-mono font-bold capitalize transition-all cursor-pointer border ${
                        sparkEmotion === emotion
                          ? 'border-primary bg-primary/10 text-primary shadow-[0_0_12px_rgba(91,142,255,0.15)]'
                          : 'border-border bg-surface text-text-2 hover:text-text-1'
                      }`}
                    >
                      {emotion}
                    </button>
                  ))}
                </div>
              </div>
            </div>

            {/* Content Column */}
            <div className="lg:col-span-7 space-y-6">
              <span className="text-xs font-mono uppercase text-accent font-bold tracking-wider">Meet the Mascot</span>
              <h3 className="font-heading text-3xl font-extrabold text-text-1 leading-tight">
                Spark: Your Responsive, CSS-Animated Study Companion
              </h3>
              <p className="text-text-2 text-xs sm:text-sm leading-relaxed">
                Learning is a journey, and we believe it deserves an emotional, engaging companion. Spark is constructed entirely from CSS and SVG layers (no static images) ensuring crisp, responsive presentation on any size screen:
              </p>
              
              <ul className="space-y-3">
                {[
                  { title: "Friendly Welcome Greetings", desc: "Spark greets you inside the dashboard and helps you initialize your onboarding goals." },
                  { title: "Confetti Completing Celebrations", desc: "When you mark a lesson as complete, Spark celebrates with confetti and tracks your streak." },
                  { title: "Adaptive Quiz Dial Score Response", desc: "Cheering you for scoring high, thinking alongside you, or encouraging a retry." },
                  { title: "Toast Milestone Slide-ins", desc: "Celebrating 3, 7, 14, and 30 day habit milestones to help maintain your momentum." }
                ].map((item, idx) => (
                  <li key={idx} className="flex items-start text-xs text-text-2">
                    <span className="h-2 w-2 rounded-full bg-accent mr-3 mt-1.5 flex-shrink-0" />
                    <div>
                      <span className="font-bold text-text-1">{item.title}</span> — {item.desc}
                    </div>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </section>

        <WhyCognara />

        {/* FAQ SECTION */}
        <section className="space-y-12">
          <div className="text-center space-y-3">
            <span className="text-xs font-mono uppercase text-primary font-bold tracking-wider">Got Questions?</span>
            <h2 className="font-heading text-3xl font-extrabold text-text-1">Frequently Asked Questions</h2>
          </div>

          <div className="max-w-3xl mx-auto space-y-4">
            {faqs.map((faq, idx) => {
              const isOpen = openFaq === idx
              return (
                <div 
                  key={idx} 
                  className="bg-surface border border-border rounded-[10px] transition-all duration-200"
                >
                  <button
                    onClick={() => setOpenFaq(isOpen ? null : idx)}
                    type="button"
                    className="w-full text-left p-5 flex items-center justify-between font-heading font-bold text-sm text-text-1 hover:text-primary transition-colors cursor-pointer"
                  >
                    <span>{faq.q}</span>
                    <HelpCircle className={`h-4 w-4 text-text-3 transition-transform ${isOpen ? 'rotate-180 text-primary' : ''}`} />
                  </button>
                  {isOpen && (
                    <div className="px-5 pb-5 pt-1 text-xs text-text-2 leading-relaxed border-t border-border/30">
                      {faq.a}
                    </div>
                  )}
                </div>
              )
            })}
          </div>
        </section>

        {/* BOTTOM CALL TO ACTION (CTA) PANEL */}
        <section className="relative overflow-hidden rounded-[16px] border border-border bg-surface p-8 md:p-12 text-center space-y-6 shadow-lg">
          <div className="absolute inset-0 bg-gradient-to-r from-primary/10 to-accent/10 pointer-events-none blur-3xl" />
          
          <div className="max-w-2xl mx-auto space-y-4 relative">
            <h2 className="font-heading text-3xl md:text-4xl font-extrabold text-text-1 tracking-tight leading-tight">
              Ready to claim your path?
            </h2>
            <p className="text-text-2 text-xs sm:text-sm leading-relaxed">
              Join thousands of self-driven learners who are building customized, adaptive roadmaps that compile around their minds.
            </p>
            <div className="pt-4">
              <Link
                href="/signup"
                className="inline-flex items-center justify-center h-12 px-8 rounded-lg font-bold text-sm bg-primary hover:bg-primary-hover text-white shadow-[0_0_20px_rgba(91,142,255,0.35)] transition-transform duration-150 hover:-translate-y-0.5"
              >
                <span>Initialize Your Operating System</span>
                <ArrowRight className="ml-2 h-4 w-4" strokeWidth={2.5} />
              </Link>
            </div>
          </div>
        </section>

      </main>

      {/* Footer */}
      <footer className="max-w-6xl w-full mx-auto px-6 pt-16 mt-16 text-center text-xs text-text-3 border-t border-border/40 relative z-10">
        &copy; {new Date().getFullYear()} Cognara. Built for modern learning operating systems. All rights reserved.
      </footer>
    </div>
  )
}
