'use client'

import React, { useState } from 'react'
import Link from 'next/link'
import {
  Map,
  BookOpen,
  Award,
  ArrowRight,
  BrainCircuit,
  Sliders,
  FileText,
  Layers,
  HelpCircle,
  Check,
  Flame,
  Grid,
  Smartphone,
  Monitor,
  Share2,
  MoreVertical,
  PlusSquare,
  WifiOff,
  Sparkles,
  Lock,
  Globe,
  Menu,
  X
} from 'lucide-react'
import { ThemeToggle } from '@/components/ui/ThemeToggle'
import { Logo } from '@/components/ui/Logo'
import { Spark } from '@/components/mascot/Spark'
import { WhyCognara } from '@/components/marketing/WhyCognara'

export default function MarketingPage() {
  // Mobile Hamburger Menu State
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false)

  // Custom JS smooth scroll handler to prevent default browser hash jump & Next.js scroll restoration
  const handleScrollToSection = (e: React.MouseEvent, id: string) => {
    e.preventDefault()
    const element = document.getElementById(id)
    if (element) {
      element.scrollIntoView({ behavior: 'smooth' })
    }
  }

  // Mascot & Simulator State
  const [sparkEmotion, setSparkEmotion] = useState<'wave' | 'happy' | 'celebrate' | 'thinking' | 'idle'>('wave')
  const [activeSubject, setActiveSubject] = useState<'tech' | 'business' | 'creative'>('tech')
  const [activeDepth, setActiveDepth] = useState<number>(3)

  // PWA Device Tab State
  const [pwaDeviceTab, setPwaDeviceTab] = useState<'apple' | 'android' | 'desktop'>('apple')

  // Pricing Billing Toggle
  const [billingPeriod, setBillingPeriod] = useState<'monthly' | 'annual'>('monthly')

  // FAQ states
  const [openFaq, setOpenFaq] = useState<number | null>(null)

  const depthLabels = ["", "Like I'm 10", "Beginner", "Intermediate", "Advanced", "Expert"]

  const subjects = [
    { id: 'tech', label: 'Tech & Code', concept: 'JavaScript Closures' },
    { id: 'business', label: 'Business & Marketing', concept: 'Customer Acquisition Cost (CAC)' },
    { id: 'creative', label: 'Creative Arts', concept: 'Color Theory in Design' }
  ] as const

  const explanations = {
    tech: [
      "",
      "Think of a closure like a magic backpack that a function carries around. Whenever the function is born, it packs all the variables from the room it was created in. Even if the function travels to a completely new place, it can unzip its backpack and grab those variables anytime!",
      "In JavaScript, a closure is a feature where a nested inner function retains access to the variables of its parent function, even after the parent function has finished running. It's like a function remembering its home town.",
      "A closure is the combination of a function bundled together with references to its surrounding state (the lexical environment). Lexical scoping determines variable access based on the physical location of declarations in the source code.",
      "Closures are heap-allocated variable environments captured during lexical parsing. When a parent context is popped off the execution stack, its activation record references are preserved in memory because the returned inner function maintains an active scope chain pointer to them.",
      "At the compiler layer (V8/SpiderMonkey), closures bypass stack allocation. The parser scans for context escaping; if a nested function references an outer binding, V8 allocates that binding in a Heap Context object rather than the Stack. The closure holds a [[Scope]] property reference, preventing GC sweep passes."
    ],
    business: [
      "",
      "Think of CAC like buying tickets to invite friends to a birthday party. If you spend $10 on party invitations and 5 friends show up, inviting each friend cost you $2! That is what CAC is—how much money you spend to get one new customer.",
      "In business, Customer Acquisition Cost (CAC) is the total amount of money a company spends to win a new customer. This includes marketing fees, sales salaries, and ads, divided by the number of customers gained.",
      "Customer Acquisition Cost (CAC) measures the efficiency of sales and marketing operations. It is computed by dividing total acquisition expenses (marketing spend, sales overhead, salaries) by the total number of acquired customers over a specific period.",
      "CAC is a critical unit economics efficiency metric. To evaluate enterprise viability, CAC must be analyzed in relation to LTV (Customer Lifetime Value) using the LTV:CAC ratio. An optimal ratio is 3:1, indicating that the gross margin generated by a customer is triple the cost to acquire them, factoring in payback periods.",
      "Analytically, CAC optimization requires dissecting marginal acquisition cost curves across paid channels. CAC is modeled as: CAC = (Total Marketing Spend + Total Sales Overheads + Customer Success Onboarding Cost) / Total Gained Customers. Dynamic cohort analysis must adjust CAC based on organic virality loops (K-factor) and churn decay coefficients."
    ],
    creative: [
      "",
      "Colors are like friends—some look super happy together, and some fight! Color Theory is a set of secret rules that artists use to mix colors so they look beautiful on your eyes. It is like matching clothes for a party!",
      "Color Theory is a set of practical guidelines for mixing colors and creating visual combinations. It uses the Color Wheel to show how primary colors (red, blue, yellow) combine to create secondary and tertiary tones that feel good to look at.",
      "Color Theory comprises the principles governing color mixing and the visual effects of specific color combinations. Underpinned by the color wheel, designers utilize contrast schemes (analogous, complementary, triadic) to create visual harmony and manage visual weight in compositions.",
      "Color Theory maps color physics and psychological perception. It defines color spaces using Hue, Saturation, and Value (HSV). Designers exploit complementary contrasts to stimulate photoreceptor cells (rods and cones) in the retina, using contrasting temperatures (warm vs cool) to establish visual hierarchy.",
      "At the intersection of optics and human perception, Color Theory is governed by additive (RGB) and subtractive (CMYK) color mixing systems. Chromatic relationships are mapped onto the CIE 1931 color space chromaticity diagram, where relative luminance contrast ratios and simultaneous contrast effects are calculated to ensure accessible visual designs."
    ]
  }

  const faqs = [
    {
      q: "Can I use Cognara to learn non-technical subjects?",
      a: "Yes! Cognara is designed to master any structured body of knowledge. Whether you are studying corporate finance, learning classical guitar, or practicing public speaking, our AI partitions the concepts, creates custom roadmaps, and adjusts explanations to your level."
    },
    {
      q: "How does Cognara know which depth level is right for me?",
      a: "During onboarding, you choose a preferred depth level. You can also change this at any time in your Settings or directly in the header of any active lesson. If a concept feels too complex or too basic, just toggle the depth to reload it immediately."
    },
    {
      q: "Does Cognara query the AI every time I load a page?",
      a: "No. Cognara uses a smart lazy-generation caching layer. The very first time you click a lesson on your roadmap, the AI compiles and structures it for your chosen depth. Once generated, it is cached in our secure database forever. This gives you instant loading times for future visits."
    },
    {
      q: "How are the daily streaks calculated?",
      a: "Your streak increases every calendar day you complete a quiz with a passing score of 60% or higher. Taking multiple quizzes on the same day maintains your streak but does not double-increment it, encouraging consistent, daily habits."
    }
  ]

  return (
    <div id="home" className="min-h-screen bg-bg text-text-1 flex flex-col relative transition-colors duration-200">
      {/* Background container for glows to prevent overflow from creating vertical whitespace */}
      <div className="absolute inset-0 overflow-hidden pointer-events-none z-0">
        <div className="absolute top-[-20%] left-[-10%] w-[600px] h-[600px] rounded-full bg-gradient-to-br from-primary/10 to-accent/15 blur-[120px] opacity-60 animate-learning-pulse" />
        <div className="absolute bottom-[-10%] right-[-5%] w-[500px] h-[500px] rounded-full bg-gradient-to-tr from-accent/10 to-primary/15 blur-[100px] opacity-50" />
      </div>

      {/* 1. Header Navigation */}
      <header className="relative z-20 max-w-7xl w-full mx-auto px-6 h-20 flex items-center justify-between border-b border-border/40 bg-bg/50 backdrop-blur-md sticky top-0">
        <a 
          href="#home" 
          onClick={(e) => handleScrollToSection(e, 'home')}
          className="flex items-center space-x-1.5 sm:space-x-2 text-primary text-text-1 hover:opacity-90 transition-opacity cursor-pointer"
        >
          <Logo className="h-5 w-5 sm:h-6 sm:w-6" />
          <span className="font-heading text-lg sm:text-xl font-bold tracking-tight text-text-1">Cognara</span>
        </a>

        {/* Marketing Anchor Navigation */}
        <nav className="hidden md:flex items-center space-x-6">
          <a 
            href="#how-it-works" 
            onClick={(e) => handleScrollToSection(e, 'how-it-works')}
            className="text-[11px] text-text-2 hover:text-text-1 font-semibold uppercase tracking-wider transition-colors duration-150"
          >
            How It Works
          </a>
          <a 
            href="#features" 
            onClick={(e) => handleScrollToSection(e, 'features')}
            className="text-[11px] text-text-2 hover:text-text-1 font-semibold uppercase tracking-wider transition-colors duration-150"
          >
            Features
          </a>
          <a 
            href="#offline-pwa" 
            onClick={(e) => handleScrollToSection(e, 'offline-pwa')}
            className="text-[11px] text-text-2 hover:text-text-1 font-semibold uppercase tracking-wider transition-colors duration-150"
          >
            Offline App
          </a>
          <a 
            href="#pricing" 
            onClick={(e) => handleScrollToSection(e, 'pricing')}
            className="text-[11px] text-text-2 hover:text-text-1 font-semibold uppercase tracking-wider transition-colors duration-150"
          >
            Pricing
          </a>
          <a 
            href="#faq" 
            onClick={(e) => handleScrollToSection(e, 'faq')}
            className="text-[11px] text-text-2 hover:text-text-1 font-semibold uppercase tracking-wider transition-colors duration-150"
          >
            FAQ
          </a>
        </nav>

        <div className="flex items-center space-x-3">
          <nav className="hidden sm:flex items-center space-x-3 sm:space-x-6">
            <Link href="/login" className="text-xs text-text-2 hover:text-text-1 font-semibold uppercase tracking-wider transition-colors duration-150">
              Sign In
            </Link>
            <Link
              href="/signup"
              className="h-8 sm:h-9 px-3 sm:px-4 inline-flex items-center justify-center rounded-md font-semibold text-[11px] sm:text-xs uppercase tracking-wider bg-primary hover:bg-primary-hover text-white transition-colors shadow-[0_0_12px_rgba(91,142,255,0.2)]"
            >
              Sign Up
            </Link>
          </nav>
          
          <ThemeToggle />

          {/* Hamburger Menu Trigger for Mobile */}
          <button
            onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
            type="button"
            className="md:hidden p-2 rounded-md hover:bg-surface-alt transition-colors text-text-1 cursor-pointer"
            aria-label="Toggle Menu"
          >
            {mobileMenuOpen ? <X className="h-5 w-5" /> : <Menu className="h-5 w-5" />}
          </button>
        </div>
      </header>

      {/* Mobile Drawer Navigation Menu */}
      {mobileMenuOpen && (
        <div className="md:hidden fixed inset-0 top-20 z-50 bg-bg/95 backdrop-blur-lg border-b border-border/40 flex flex-col p-6 space-y-6 animate-page-enter">
          <nav className="flex flex-col space-y-4">
            <a 
              href="#how-it-works" 
              onClick={(e) => {
                setMobileMenuOpen(false)
                handleScrollToSection(e, 'how-it-works')
              }}
              className="text-sm text-text-2 hover:text-text-1 font-semibold uppercase tracking-wider py-2 border-b border-border/30"
            >
              How It Works
            </a>
            <a 
              href="#features" 
              onClick={(e) => {
                setMobileMenuOpen(false)
                handleScrollToSection(e, 'features')
              }}
              className="text-sm text-text-2 hover:text-text-1 font-semibold uppercase tracking-wider py-2 border-b border-border/30"
            >
              Features
            </a>
            <a 
              href="#offline-pwa" 
              onClick={(e) => {
                setMobileMenuOpen(false)
                handleScrollToSection(e, 'offline-pwa')
              }}
              className="text-sm text-text-2 hover:text-text-1 font-semibold uppercase tracking-wider py-2 border-b border-border/30"
            >
              Offline App
            </a>
            <a 
              href="#pricing" 
              onClick={(e) => {
                setMobileMenuOpen(false)
                handleScrollToSection(e, 'pricing')
              }}
              className="text-sm text-text-2 hover:text-text-1 font-semibold uppercase tracking-wider py-2 border-b border-border/30"
            >
              Pricing
            </a>
            <a 
              href="#faq" 
              onClick={(e) => {
                setMobileMenuOpen(false)
                handleScrollToSection(e, 'faq')
              }}
              className="text-sm text-text-2 hover:text-text-1 font-semibold uppercase tracking-wider py-2 border-b border-border/30"
            >
              FAQ
            </a>
          </nav>
          
          <div className="flex flex-col gap-3 pt-4 border-t border-border/40">
            <Link 
              href="/login"
              onClick={() => setMobileMenuOpen(false)}
              className="w-full h-11 border border-border bg-surface hover:bg-surface-alt text-text-1 flex items-center justify-center rounded-lg font-bold text-xs uppercase tracking-wider"
            >
              Sign In
            </Link>
            <Link 
              href="/signup"
              onClick={() => setMobileMenuOpen(false)}
              className="w-full h-11 bg-primary hover:bg-primary-hover text-white flex items-center justify-center rounded-lg font-bold text-xs uppercase tracking-wider"
            >
              Sign Up
            </Link>
          </div>
        </div>
      )}

      {/* 2. Main content container */}
      <main className="relative z-10 max-w-6xl w-full mx-auto px-6 mt-12 md:mt-20">

        {/* HERO SECTION */}
        <section className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-center py-20 md:py-28">
          <div className="lg:col-span-7 space-y-6 text-left">
            <span className="inline-flex items-center px-3 py-1 border border-accent/20 bg-accent/5 text-accent text-xs font-mono font-bold uppercase tracking-widest rounded-full">
              Your mind. Your path. Your era.
            </span>
            <h1 className="font-heading text-4xl sm:text-5xl md:text-6xl font-extrabold text-text-1 tracking-tight leading-[1.05]">
              Master Anything. <br />
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-primary to-accent">Calibrated to You.</span>
            </h1>
            <p className="text-text-2 text-sm sm:text-base leading-relaxed max-w-xl">
              Cognara is an AI Learning Operating System. We dynamically compile your learning goals into logical roadmaps, rendering rich lesson layouts and adaptive quiz challenges engineered around your personal schedule and explanation depth.
            </p>

            <div className="flex flex-col sm:flex-row items-center gap-4 pt-4">
              <Link
                href="/signup"
                className="w-full sm:w-auto h-12 px-8 inline-flex items-center justify-center rounded-lg font-bold text-sm bg-primary hover:bg-primary-hover text-white shadow-[0_0_20px_rgba(91,142,255,0.3)] transition-all duration-150 hover:-translate-y-0.5"
              >
                <span>Start Learning For Free</span>
                <ArrowRight className="ml-2 h-4 w-4" strokeWidth={2.5} />
              </Link>
              <Link
                href="/login"
                className="w-full sm:w-auto h-12 px-8 inline-flex items-center justify-center rounded-lg font-bold text-sm border border-border bg-surface hover:bg-surface-alt text-text-1 transition-all duration-150"
              >
                Sign In to Dashboard
              </Link>
            </div>
          </div>

          {/* Hero Visual Card (Visual Showcase Mockup) */}
          <div className="lg:col-span-5 relative">
            <div className="absolute inset-0 bg-gradient-to-r from-primary/10 to-accent/10 rounded-[12px] blur-xl pointer-events-none" />
            <div className="relative bg-surface border border-border rounded-[12px] p-5 shadow-lg space-y-4">
              <div className="flex items-center justify-between border-b border-border pb-3">
                <div className="flex items-center space-x-1.5">
                  <span className="w-3 h-3 rounded-full bg-error" />
                  <span className="w-3 h-3 rounded-full bg-accent-warm" />
                  <span className="w-3 h-3 rounded-full bg-success" />
                </div>
                <span className="text-[9px] font-mono text-text-3">ROADMAP CONFIGURATION</span>
              </div>
              <div className="space-y-3">
                <div className="flex items-center justify-between">
                  <span className="text-xs text-text-2">Target Goal</span>
                  <span className="text-xs text-text-1 font-semibold">Business Finance & Strategy</span>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-xs text-text-2">Study Schedule</span>
                  <span className="text-xs text-text-1 font-semibold">30 minutes / day</span>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-xs text-text-2">Subject Area</span>
                  <span className="text-xs text-text-1 font-semibold">Corporate Economics</span>
                </div>
              </div>
              <div className="p-3 bg-surface-alt border border-border/60 rounded-[8px] space-y-2">
                <div className="flex items-center justify-between">
                  <span className="text-[10px] font-mono text-accent font-bold">COMPILING CURRICULUM</span>
                  <span className="text-[10px] font-mono text-text-3">100%</span>
                </div>
                <div className="w-full bg-border h-1.5 rounded-full overflow-hidden">
                  <div className="bg-primary h-full w-full rounded-full" />
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* DASHBOARD PREVIEW SHOWCASE */}
        <section className="space-y-6 animate-page-enter py-20 md:py-28">
          <div className="text-center max-w-2xl mx-auto space-y-2">
            <span className="text-xs font-mono uppercase text-accent font-bold tracking-wider">Product Tour</span>
            <h2 className="font-heading text-2xl sm:text-3xl font-extrabold text-text-1">A Clean, Focused Learning OS</h2>
            <p className="text-text-2 text-xs sm:text-sm">
              Manage your milestones, track learning vitals, and receive custom coach insights inside a responsive dashboard.
            </p>
          </div>

          <div className="relative rounded-[16px] border border-border bg-surface p-2 shadow-2xl overflow-hidden group max-w-5xl mx-auto">
            {/* Ambient background glow */}
            <div className="absolute -inset-10 bg-gradient-to-r from-primary/10 to-accent/10 rounded-[24px] blur-3xl pointer-events-none opacity-50 group-hover:opacity-75 transition-opacity duration-500" />

            <div className="relative rounded-[12px] overflow-hidden border border-border/60">
              <img
                src="/images/dashboard-light.png"
                alt="Cognara Dashboard Light Mode"
                className="w-full h-auto block dark:hidden object-cover transition-all duration-700 ease-out group-hover:scale-[1.005]"
              />
              <img
                src="/images/dashboard-dark.png"
                alt="Cognara Dashboard Dark Mode"
                className="w-full h-auto hidden dark:block object-cover transition-all duration-700 ease-out group-hover:scale-[1.005]"
              />
            </div>
          </div>
        </section>

        {/* 3-STEP WALKTHROUGH SECTION */}
        <section id="how-it-works" className="space-y-12 py-20 md:py-28 scroll-mt-24">
          <div className="text-center space-y-3">
            <span className="text-xs font-mono uppercase text-primary font-bold tracking-wider">How it works</span>
            <h2 className="font-heading text-3xl font-extrabold text-text-1">A Blueprint Designed For Your Mind</h2>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="p-6 bg-surface border border-border rounded-[10px] space-y-4 shadow-sm flex flex-col justify-between">
              <div className="space-y-3">
                <div className="w-10 h-10 rounded-md bg-primary/10 text-primary flex items-center justify-center border border-primary/15 font-heading font-bold text-base">
                  01
                </div>
                <h3 className="font-heading text-lg font-bold text-text-1">State Your Aspirations</h3>
                <p className="text-text-2 text-xs leading-relaxed">
                  Enter any skill, domain, or subject you wish to master—from software engineering and marketing curves to culinary arts or language practice.
                </p>
              </div>
            </div>

            <div className="p-6 bg-surface border border-border rounded-[10px] space-y-4 shadow-sm flex flex-col justify-between">
              <div className="space-y-3">
                <div className="w-10 h-10 rounded-md bg-accent/10 text-accent flex items-center justify-center border border-accent/15 font-heading font-bold text-base">
                  02
                </div>
                <h3 className="font-heading text-lg font-bold text-text-1">Dynamic Roadmap Partitioning</h3>
                <p className="text-text-2 text-xs leading-relaxed">
                  Our compiler constructs a logical track of modules and milestones, creating lazy-generation lesson stubs ready for your studies.
                </p>
              </div>
            </div>

            <div className="p-6 bg-surface border border-border rounded-[10px] space-y-4 shadow-sm flex flex-col justify-between">
              <div className="space-y-3">
                <div className="w-10 h-10 rounded-md bg-success/10 text-success flex items-center justify-center border border-success/15 font-heading font-bold text-base">
                  03
                </div>
                <h3 className="font-heading text-lg font-bold text-text-1">Adaptive Depth Loading</h3>
                <p className="text-text-2 text-xs leading-relaxed">
                  Open any lesson stub. Toggle explanation layers from simplified analogies to heap memory compiler logic instantly.
                </p>
              </div>
            </div>
          </div>
        </section>

        {/* INTERACTIVE DEMONSTRATOR: ADAPTIVE DEPTH SIMULATOR */}
        <div id="features" className="py-20 md:py-28 scroll-mt-24">
          <section className="bg-surface border border-border rounded-[12px] p-6 md:p-8 space-y-8 shadow-md relative overflow-hidden">
          <div className="absolute right-0 top-0 w-36 h-36 rounded-full bg-primary/5 blur-2xl pointer-events-none" />

          <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-center">
            <div className="lg:col-span-5 space-y-4">
              <div className="inline-flex items-center space-x-1.5 text-accent font-mono text-xs uppercase tracking-wider font-bold">
                <Sliders className="h-4 w-4" />
                <span>Feature Showcase</span>
              </div>
              <h3 className="font-heading text-2xl font-bold tracking-tight text-text-1 leading-tight">
                Adaptive Explanation Depth
              </h3>
              <p className="text-text-2 text-xs leading-relaxed">
                Watch how Cognara re-structures explanations across 5 distinct cognitive levels. Select a domain tab and click on the depths to see the explanation transform.
              </p>

              {/* Category tabs */}
              <div className="flex flex-col space-y-2 pt-2">
                <span className="text-[10px] font-mono text-text-3 uppercase tracking-wider">Select Domain</span>
                <div className="flex flex-col sm:flex-row gap-2">
                  {subjects.map((sub) => (
                    <button
                      key={sub.id}
                      onClick={() => {
                        setActiveSubject(sub.id)
                        setActiveDepth(3) // reset depth to intermediate
                      }}
                      type="button"
                      className={`px-3 py-2 text-left rounded-md border text-xs font-semibold transition-all cursor-pointer ${activeSubject === sub.id
                        ? 'border-primary bg-primary/5 text-primary'
                        : 'border-border bg-surface-alt text-text-2 hover:text-text-1'
                        }`}
                    >
                      {sub.label}
                    </button>
                  ))}
                </div>
              </div>
            </div>

            {/* Simulated UI window */}
            <div className="lg:col-span-7 space-y-4">
              {/* Depth Toggles Header */}
              <div className="flex flex-wrap gap-2 border-b border-border pb-3 justify-start">
                {[1, 2, 3, 4, 5].map((lvl) => (
                  <button
                    key={lvl}
                    onClick={() => setActiveDepth(lvl)}
                    type="button"
                    className={`px-3 py-1.5 rounded-sm font-mono text-[10px] uppercase font-bold tracking-wide transition-all cursor-pointer ${activeDepth === lvl
                      ? 'bg-primary text-white shadow-[0_0_12px_rgba(91,142,255,0.25)]'
                      : 'bg-surface-alt border border-border text-text-2 hover:text-text-1'
                      }`}
                  >
                    <span>Lvl {lvl}</span>
                  </button>
                ))}
              </div>

              {/* Display Box */}
              <div className="p-5 bg-surface-alt border border-border/80 rounded-[8px] space-y-3 min-h-[160px] flex flex-col justify-between border-l-2 border-l-accent">
                {/* Header Row with Heading and Badge */}
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 border-b border-border/30 pb-2">
                  <h4 className="font-heading text-sm font-bold text-text-1">
                    Concept: {subjects.find(s => s.id === activeSubject)?.concept}
                  </h4>
                  <div className="opacity-75">
                    <span className="inline-flex items-center px-1.5 py-0.5 border border-accent/20 bg-accent/5 text-accent text-[8px] font-mono font-bold uppercase rounded-sm">
                      GENERATED — Lvl {activeDepth} ({depthLabels[activeDepth]})
                    </span>
                  </div>
                </div>
                <p className="text-text-2 text-xs leading-relaxed whitespace-pre-line pr-2 flex-1">
                  {explanations[activeSubject][activeDepth]}
                </p>
              </div>
            </div>
          </div>
          </section>
        </div>

        {/* RICH CONTENT SYSTEM PREVIEW */}
        <section className="grid grid-cols-1 lg:grid-cols-2 gap-8 items-center py-20 md:py-28">
          <div className="space-y-6">
            <span className="text-xs font-mono uppercase text-primary font-bold tracking-wider">Rich Layout Engine</span>
            <h3 className="font-heading text-3xl font-extrabold text-text-1 leading-tight">
              Lessons Must Not Be Walls of Text.
            </h3>
            <p className="text-text-2 text-xs sm:text-sm leading-relaxed">
              Every concept requires the correct pedagogical representation. Cognara's layout engine dynamically injects custom structural blocks to ensure concepts click immediately:
            </p>

            <ul className="space-y-3">
              {[
                { title: "Monaco Code Practice Playgrounds", desc: "Live code editor with syntax highlighting for hands-on technical lessons (HTML/CSS/JS)." },
                { title: "AI Soft-Skills Writing Workspaces", desc: "Advanced text area with instant, context-aware AI feedback for paragraph assignments." },
                { title: "Actionable Task Checklists", desc: "Visual, step-by-step guides for practical offline training exercises." },
                { title: "Interactive Spark Mascot Greetings", desc: "A CSS/SVG animated AI companion that celebrates your study wins and habit streaks." },
                { title: "Progressive Subscription Paywalls", desc: "Freemium plan layout options and structured limits tailored for active goals." },
                { title: "Colored Context Callouts", desc: "Important, Warning, Tip, and Pro Tip callouts highlighting critical concepts." }
              ].map((item, idx) => (
                <li key={idx} className="flex items-start text-xs text-text-2">
                  <Check className="h-4 w-4 text-success mr-2.5 flex-shrink-0 mt-0.5" strokeWidth={3} />
                  <div>
                    <span className="font-bold text-text-1">{item.title}</span> — {item.desc}
                  </div>
                </li>
              ))}
            </ul>
          </div>

          {/* Graphical representation grid */}
          <div className="grid grid-cols-2 gap-4">
            <div className="p-4 bg-surface border border-border rounded-[10px] space-y-2 shadow-sm">
              <span className="text-[8px] font-mono text-accent">TIP CALLOUT</span>
              <div className="text-xs font-bold text-text-1">💡 Focus on Payback Periods</div>
              <p className="text-[10px] text-text-2 leading-relaxed">When analyzing CAC, prioritize payback periods. A low CAC is risky if payback takes over 12 months.</p>
            </div>

            <div className="p-4 bg-surface border border-border rounded-[10px] space-y-3 shadow-sm">
              <span className="text-[8px] font-mono text-accent">DIAGRAM BLOCK</span>
              <pre className="text-[9px] font-mono text-text-2 leading-tight">
                {`[Target Audience]
   └── conversion 
         └── [Acquired User]`}</pre>
            </div>

            <div className="p-4 bg-surface border border-border rounded-[10px] space-y-2 shadow-sm col-span-2">
              <span className="text-[8px] font-mono text-accent">COMPARISON TABLE</span>
              <div className="grid grid-cols-2 gap-2 text-[9px] font-mono">
                <div className="p-2 bg-error/5 border border-error/15 text-error rounded-sm">❌ High CAC (Sales heavy)</div>
                <div className="p-2 bg-success/5 border border-success/15 text-success rounded-sm">✅ Low CAC (Word of Mouth)</div>
              </div>
            </div>
          </div>
        </section>

        {/* PROGRESS & COACH WIDGET SHOWCASE */}
        <div className="py-20 md:py-28">
          <section className="bg-surface border border-border rounded-[12px] p-6 md:p-8 space-y-8 shadow-md">
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-center">

            {/* Visual Dashboard Card Mockup */}
            <div className="lg:col-span-6 space-y-4 order-last lg:order-first">
              <div className="p-5 bg-surface-alt border border-border/80 rounded-[8px] space-y-4">
                <div className="flex items-center justify-between border-b border-border pb-3">
                  <div className="flex items-center space-x-2">
                    <Flame className="h-4 w-4 text-accent-warm fill-current" />
                    <span className="text-[10px] font-mono text-text-1 font-bold">12-DAY STUDY STREAK</span>
                  </div>
                  <span className="text-[9px] font-mono text-text-3">ANALYTICS ENGINE</span>
                </div>
                {/* Visual Heatmap Mock */}
                <div className="space-y-2">
                  <div className="text-[8px] font-mono text-text-3 uppercase">Activity Calendar</div>
                  <div className="flex gap-1">
                    {[1, 2, 0, 3, 1, 0, 2, 3, 3, 1, 2, 0, 1, 3, 2, 0, 1].map((val, i) => {
                      let color = 'bg-border/40'
                      if (val === 1) color = 'bg-primary/25'
                      if (val === 2) color = 'bg-primary/50'
                      if (val === 3) color = 'bg-primary'
                      return <div key={i} className={`w-3.5 h-3.5 rounded-sm ${color}`} />
                    })}
                  </div>
                </div>
                {/* AI Coach card Mock */}
                <div className="border-l-[3px] border-accent bg-accent/5 p-3.5 rounded-r-[8px] space-y-1">
                  <span className="text-[8px] font-mono text-accent font-bold uppercase tracking-wider">AI Coach Insight</span>
                  <p className="text-[10px] text-text-1 leading-normal">
                    You're doing great! Your quiz accuracy trajectory is at 88%. You mastered Customer Acquisition Cost calculations today. Continue to LTV ratios tomorrow.
                  </p>
                </div>
              </div>
            </div>

            <div className="lg:col-span-6 space-y-6">
              <span className="text-xs font-mono uppercase text-primary font-bold tracking-wider">Analytics & Coach</span>
              <h3 className="font-heading text-3xl font-extrabold text-text-1 leading-tight">
                Streaks, Heatmaps, and Personalized Insights.
              </h3>
              <p className="text-text-2 text-xs sm:text-sm leading-relaxed">
                Stay motivated with interactive vitals metrics. Cognara logs your daily studies and quiz scores, generating a GitHub-style activity heatmap, score charts, and direct coach feedback to highlight strengths and recommend reviews.
              </p>
            </div>
          </div>
          </section>
        </div>

        {/* INTERACTIVE MASCOT SHOWCASE */}
        <div className="py-20 md:py-28">
          <section className="bg-surface border border-border rounded-[12px] p-6 md:p-8 space-y-8 shadow-md relative overflow-hidden">
          <div className="absolute left-0 top-0 w-36 h-36 rounded-full bg-accent/5 blur-2xl pointer-events-none" />

          <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-center">

            {/* Spark mascot column */}
            <div className="lg:col-span-5 flex flex-col items-center justify-center p-6 bg-surface-alt border border-border/60 rounded-[8px] min-h-[300px] relative">
              <div className="mb-6 flex justify-center items-center w-full">
                <Spark emotion={sparkEmotion} size={120} />
              </div>

              <div className="w-full space-y-3">
                <span className="text-[10px] font-mono text-text-3 uppercase tracking-wider block text-center">Tap to Change Spark's Emotion</span>
                <div className="flex flex-wrap gap-2 justify-center">
                  {(['wave', 'happy', 'celebrate', 'thinking', 'idle'] as const).map((emotion) => (
                    <button
                      key={emotion}
                      onClick={() => setSparkEmotion(emotion)}
                      type="button"
                      className={`px-2.5 py-1 rounded-md text-[10px] font-mono font-bold capitalize transition-all cursor-pointer border ${sparkEmotion === emotion
                        ? 'border-primary bg-primary/10 text-primary shadow-[0_0_12px_rgba(91,142,255,0.15)]'
                        : 'border-border bg-surface text-text-2 hover:text-text-1'
                        }`}
                    >
                      {emotion}
                    </button>
                  ))}
                </div>
              </div>
            </div>

            {/* Content Column */}
            <div className="lg:col-span-7 space-y-6">
              <span className="text-xs font-mono uppercase text-accent font-bold tracking-wider">Meet the Mascot</span>
              <h3 className="font-heading text-3xl font-extrabold text-text-1 leading-tight">
                Spark: Your Responsive, CSS-Animated Study Companion
              </h3>
              <p className="text-text-2 text-xs sm:text-sm leading-relaxed">
                Learning is a journey, and we believe it deserves an emotional, engaging companion. Spark is constructed entirely from CSS and SVG layers (no static images) ensuring crisp, responsive presentation on any size screen:
              </p>

              <ul className="space-y-3">
                {[
                  { title: "Friendly Welcome Greetings", desc: "Spark greets you inside the dashboard and helps you initialize your onboarding goals." },
                  { title: "Confetti Completing Celebrations", desc: "When you mark a lesson as complete, Spark celebrates with confetti and tracks your streak." },
                  { title: "Adaptive Quiz Dial Score Response", desc: "Cheering you for scoring high, thinking alongside you, or encouraging a retry." },
                  { title: "Toast Milestone Slide-ins", desc: "Celebrating 3, 7, 14, and 30 day habit milestones to help maintain your momentum." }
                ].map((item, idx) => (
                  <li key={idx} className="flex items-start text-xs text-text-2">
                    <span className="h-2 w-2 rounded-full bg-accent mr-3 mt-1.5 flex-shrink-0" />
                    <div>
                      <span className="font-bold text-text-1">{item.title}</span> — {item.desc}
                    </div>
                  </li>
                ))}
              </ul>
            </div>
          </div>
          </section>
        </div>

        {/* PWA INSTALLATION SECTION */}
        <section id="offline-pwa" className="py-20 md:py-28 animate-page-enter scroll-mt-24">
          <div className="bg-surface border border-border rounded-[12px] p-6 md:p-8 space-y-8 shadow-md relative overflow-hidden">
            <div className="absolute right-0 top-0 w-36 h-36 rounded-full bg-primary/5 blur-2xl pointer-events-none" />
            
            <div className="text-center max-w-2xl mx-auto space-y-3 mb-10">
              <span className="inline-flex items-center px-3 py-1 border border-primary/20 bg-primary/5 text-primary text-xs font-mono font-bold uppercase tracking-widest rounded-full">
                Progressive Web App (PWA)
              </span>
              <h2 className="font-heading text-2xl sm:text-3xl font-extrabold text-text-1">
                Install Cognara. Study Anywhere, Offline.
              </h2>
              <p className="text-text-2 text-xs sm:text-sm max-w-xl mx-auto leading-relaxed">
                Save Cognara directly to your device home screen as a native application. Read your downloaded lessons, track your streaks, and navigate your path—all with zero internet connection.
              </p>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-stretch">
              {/* Left Side: PWA features description */}
              <div className="lg:col-span-5 space-y-6 flex flex-col justify-center">
                <h3 className="font-heading text-lg font-bold text-text-1">Why install the PWA?</h3>
                <div className="space-y-4">
                  <div className="flex items-start space-x-3.5">
                    <div className="w-8 h-8 rounded-lg bg-primary/10 border border-primary/20 flex items-center justify-center text-primary shrink-0">
                      <WifiOff className="h-4 w-4" />
                    </div>
                    <div>
                      <h4 className="text-xs font-bold text-text-1">Full Offline Reading</h4>
                      <p className="text-[11px] text-text-2 leading-relaxed mt-0.5">
                        Open the app without internet to browse your downloaded lessons shelf. Learn on flights, commutes, or remote locations without distractions.
                      </p>
                    </div>
                  </div>

                  <div className="flex items-start space-x-3.5">
                    <div className="w-8 h-8 rounded-lg bg-accent/10 border border-accent/20 flex items-center justify-center text-accent shrink-0">
                      <Layers className="h-4 w-4" />
                    </div>
                    <div>
                      <h4 className="text-xs font-bold text-text-1">Native Fullscreen Layout</h4>
                      <p className="text-[11px] text-text-2 leading-relaxed mt-0.5">
                        Banish browser address bars, tabs, and navigation controls. Enjoy 100% focused viewport space dedicated purely to studying.
                      </p>
                    </div>
                  </div>

                  <div className="flex items-start space-x-3.5">
                    <div className="w-8 h-8 rounded-lg bg-success/10 border border-success/20 flex items-center justify-center text-success shrink-0">
                      <Flame className="h-4 w-4" />
                    </div>
                    <div>
                      <h4 className="text-xs font-bold text-text-1">Instant App Shell Loading</h4>
                      <p className="text-[11px] text-text-2 leading-relaxed mt-0.5">
                        Our service worker pre-caches static layout elements, icons, assets, and custom fonts, making subsequent loads instant even on slow connections.
                      </p>
                    </div>
                  </div>
                </div>
              </div>

              {/* Right Side: Interactive Device Installation Steps */}
              <div className="lg:col-span-7 flex flex-col border border-border/80 bg-surface-alt/40 rounded-xl p-5 md:p-6 space-y-6">
                <div className="flex flex-col space-y-2.5">
                  <span className="text-[10px] font-mono text-text-3 uppercase tracking-wider">Device Guides</span>
                  {/* Tabs bar */}
                  <div className="flex border border-border/85 bg-surface rounded-lg p-0.5 overflow-hidden">
                    {[
                      { id: 'apple', label: 'Apple iOS', icon: Smartphone },
                      { id: 'android', label: 'Android', icon: Smartphone },
                      { id: 'desktop', label: 'Desktop App', icon: Monitor }
                    ].map((tab) => {
                      const TabIcon = tab.icon
                      const isActive = pwaDeviceTab === tab.id
                      return (
                        <button
                          key={tab.id}
                          onClick={() => setPwaDeviceTab(tab.id as any)}
                          type="button"
                          className={`flex-1 flex items-center justify-center gap-1.5 py-2 px-1 text-xs font-semibold rounded-md transition-all cursor-pointer ${
                            isActive
                              ? 'bg-primary text-white shadow-xs'
                              : 'text-text-2 hover:text-text-1 hover:bg-surface-alt/50'
                          }`}
                        >
                          <TabIcon className="h-3.5 w-3.5" />
                          <span>{tab.label}</span>
                        </button>
                      )
                    })}
                  </div>
                </div>

                {/* Tab content area */}
                <div className="flex-1 bg-surface border border-border/70 rounded-lg p-4 md:p-5 flex flex-col justify-between min-h-[220px]">
                  {pwaDeviceTab === 'apple' && (
                    <div className="space-y-4">
                      <div className="flex items-center gap-2 border-b border-border/40 pb-2.5">
                        <Smartphone className="h-4 w-4 text-primary" />
                        <span className="text-xs font-bold text-text-1">Install on iPhone & iPad (Safari)</span>
                      </div>
                      <ol className="space-y-3 text-[11px] text-text-2 pl-1 break-words">
                        <li className="flex items-start">
                          <span className="w-4 h-4 rounded-full bg-primary/10 border border-primary/20 text-primary flex items-center justify-center font-bold text-[9px] mr-2 shrink-0 mt-0.5">1</span>
                          <span>Open the **Safari** browser and navigate to <code className="px-1 py-0.5 bg-surface-alt border border-border rounded text-[10px] font-mono break-all">cognaralearn.com/dashboard</code> (or the app URL).</span>
                        </li>
                        <li className="flex items-start">
                          <span className="w-4 h-4 rounded-full bg-primary/10 border border-primary/20 text-primary flex items-center justify-center font-bold text-[9px] mr-2 shrink-0 mt-0.5">2</span>
                          <span>Tap the **Share** button <Share2 className="h-3.5 w-3.5 inline mx-0.5 text-text-2" /> (the square icon with an arrow pointing up at the bottom of the screen).</span>
                        </li>
                        <li className="flex items-start">
                          <span className="w-4 h-4 rounded-full bg-primary/10 border border-primary/20 text-primary flex items-center justify-center font-bold text-[9px] mr-2 shrink-0 mt-0.5">3</span>
                          <span>Scroll down the options menu and select **Add to Home Screen** <PlusSquare className="h-3.5 w-3.5 inline mx-0.5 text-text-2" />.</span>
                        </li>
                        <li className="flex items-start">
                          <span className="w-4 h-4 rounded-full bg-primary/10 border border-primary/20 text-primary flex items-center justify-center font-bold text-[9px] mr-2 shrink-0 mt-0.5">4</span>
                          <span>Tap **Add** in the top right corner. The Cognara diamond app icon will be installed on your Home Screen.</span>
                        </li>
                      </ol>
                    </div>
                  )}

                  {pwaDeviceTab === 'android' && (
                    <div className="space-y-4">
                      <div className="flex items-center gap-2 border-b border-border/40 pb-2.5">
                        <Smartphone className="h-4 w-4 text-primary" />
                        <span className="text-xs font-bold text-text-1">Install on Android Device (Chrome)</span>
                      </div>
                      <ol className="space-y-3 text-[11px] text-text-2 pl-1">
                        <li className="flex items-start">
                          <span className="w-4 h-4 rounded-full bg-primary/10 border border-primary/20 text-primary flex items-center justify-center font-bold text-[9px] mr-2 shrink-0 mt-0.5">1</span>
                          <span>Open Google **Chrome** and navigate to your dashboard/app URL.</span>
                        </li>
                        <li className="flex items-start">
                          <span className="w-4 h-4 rounded-full bg-primary/10 border border-primary/20 text-primary flex items-center justify-center font-bold text-[9px] mr-2 shrink-0 mt-0.5">2</span>
                          <span>Tap the **Menu** icon <MoreVertical className="h-3.5 w-3.5 inline mx-0.5 text-text-2" /> (three vertical dots in the top-right corner of Chrome).</span>
                        </li>
                        <li className="flex items-start">
                          <span className="w-4 h-4 rounded-full bg-primary/10 border border-primary/20 text-primary flex items-center justify-center font-bold text-[9px] mr-2 shrink-0 mt-0.5">3</span>
                          <span>Tap **Install app** or **Add to Home screen** from the menu options.</span>
                        </li>
                        <li className="flex items-start">
                          <span className="w-4 h-4 rounded-full bg-primary/10 border border-primary/20 text-primary flex items-center justify-center font-bold text-[9px] mr-2 shrink-0 mt-0.5">4</span>
                          <span>Confirm by tapping **Install** in the popup. The app will install in the background and appear in your launcher drawer.</span>
                        </li>
                      </ol>
                    </div>
                  )}

                  {pwaDeviceTab === 'desktop' && (
                    <div className="space-y-4">
                      <div className="flex items-center gap-2 border-b border-border/40 pb-2.5">
                        <Monitor className="h-4 w-4 text-primary" />
                        <span className="text-xs font-bold text-text-1">Install on PC, Mac, or Chromebook (Chrome/Edge)</span>
                      </div>
                      <ol className="space-y-3 text-[11px] text-text-2 pl-1">
                        <li className="flex items-start">
                          <span className="w-4 h-4 rounded-full bg-primary/10 border border-primary/20 text-primary flex items-center justify-center font-bold text-[9px] mr-2 shrink-0 mt-0.5">1</span>
                          <span>Open Google **Chrome**, **Microsoft Edge**, or **Brave** and log in to Cognara.</span>
                        </li>
                        <li className="flex items-start">
                          <span className="w-4 h-4 rounded-full bg-primary/10 border border-primary/20 text-primary flex items-center justify-center font-bold text-[9px] mr-2 shrink-0 mt-0.5">2</span>
                          <span>Look at the right side of the address bar at the top (next to the bookmark star). You will see the **PWA Install icon** (a monitor with a down arrow, or a plus icon).</span>
                        </li>
                        <li className="flex items-start">
                          <span className="w-4 h-4 rounded-full bg-primary/10 border border-primary/20 text-primary flex items-center justify-center font-bold text-[9px] mr-2 shrink-0 mt-0.5">3</span>
                          <span>Click the install icon, and click **Install** when the system prompt appears.</span>
                        </li>
                        <li className="flex items-start">
                          <span className="w-4 h-4 rounded-full bg-primary/10 border border-primary/20 text-primary flex items-center justify-center font-bold text-[9px] mr-2 shrink-0 mt-0.5">4</span>
                          <span>The app will immediately open in a dedicated standalone window. A launch shortcut will be placed on your desktop for quick double-click access.</span>
                        </li>
                      </ol>
                    </div>
                  )}
                  
                  {/* Decorative badge */}
                  <div className="mt-4 pt-3.5 border-t border-border/40 flex items-center justify-between text-[9px] font-mono text-text-3">
                    <span>SECURE AND LIGHTWEIGHT</span>
                    <span className="text-success font-bold">● ONLINE / OFFLINE DETECTED</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        <WhyCognara />

        {/* PRICING SECTION */}
        <section id="pricing" className="py-20 md:py-28 animate-page-enter scroll-mt-24">
          <div className="text-center max-w-2xl mx-auto space-y-3 mb-10">
            <span className="inline-flex items-center px-3 py-1 border border-accent/20 bg-accent/5 text-accent text-xs font-mono font-bold uppercase tracking-widest rounded-full">
              Flexible Plans
            </span>
            <h2 className="font-heading text-2xl sm:text-3xl font-extrabold text-text-1">
              Simple, Transparent Pricing
            </h2>
            <p className="text-text-2 text-xs sm:text-sm max-w-xl mx-auto leading-relaxed">
              Start learning for free and upgrade to Pro whenever you need unlimited goals, academic-grade depth levels, and offline reading.
            </p>

            {/* Monthly / Annual Toggle */}
            <div className="flex items-center justify-center pt-4">
              <div className="bg-surface border border-border p-1 rounded-lg flex items-center gap-1">
                <button
                  type="button"
                  onClick={() => setBillingPeriod('monthly')}
                  className={`px-4 py-1.5 rounded-md text-xs font-semibold transition-all cursor-pointer ${
                    billingPeriod === 'monthly'
                      ? 'bg-primary text-white shadow-sm'
                      : 'text-text-2 hover:text-text-1'
                  }`}
                >
                  Monthly
                </button>
                <button
                  type="button"
                  onClick={() => setBillingPeriod('annual')}
                  className={`px-4 py-1.5 rounded-md text-xs font-semibold transition-all flex items-center gap-1 cursor-pointer ${
                    billingPeriod === 'annual'
                      ? 'bg-primary text-white shadow-sm'
                      : 'text-text-2 hover:text-text-1'
                  }`}
                >
                  <span>Annual</span>
                  <span className="text-[9px] bg-accent-warm text-black font-mono font-bold px-1 rounded-sm uppercase tracking-wide">Save 16%</span>
                </button>
              </div>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-8 max-w-4xl mx-auto items-stretch">
            {/* Card 1: Free Tier */}
            <div className="bg-surface border border-border rounded-2xl p-6 md:p-8 flex flex-col justify-between space-y-8 relative overflow-hidden transition-all hover:border-border-hover">
              <div className="space-y-6">
                <div>
                  <h3 className="font-heading text-lg font-bold text-text-1">Free Tier</h3>
                  <p className="text-text-2 text-xs mt-1">Perfect for trying out Cognara's personalized roadmaps.</p>
                </div>
                <div className="flex items-baseline">
                  <span className="font-heading text-3xl font-extrabold text-text-1">₦0</span>
                  <span className="text-text-2 text-xs ml-1.5 font-semibold">/ forever</span>
                </div>
                <div className="w-full h-px bg-border/60" />
                <ul className="space-y-3.5 text-xs text-text-2">
                  <li className="flex items-center gap-2">
                    <Check className="h-4 w-4 text-success shrink-0" strokeWidth={2.5} />
                    <span>1 Active Learning Goal</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <Check className="h-4 w-4 text-success shrink-0" strokeWidth={2.5} />
                    <span>Beginner Depth Level Only (Level 2)</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <Check className="h-4 w-4 text-success shrink-0" strokeWidth={2.5} />
                    <span>Standard AI Lesson Generation</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <Check className="h-4 w-4 text-success shrink-0" strokeWidth={2.5} />
                    <span>Interactive Practice Quizzes</span>
                  </li>
                </ul>
              </div>
              <Link href="/signup" className="w-full">
                <button className="w-full py-3 border border-border hover:bg-surface-alt font-bold rounded-lg text-xs transition duration-150 cursor-pointer text-text-1">
                  Get Started For Free
                </button>
              </Link>
            </div>

            {/* Card 2: Pro Tier */}
            <div className="bg-gradient-to-br from-surface via-surface to-primary/5 border-2 border-primary rounded-2xl p-6 md:p-8 flex flex-col justify-between space-y-8 relative overflow-hidden shadow-[0_0_24px_rgba(91,142,255,0.08)]">
              <div className="absolute top-0 right-0 h-4 bg-primary text-white font-mono font-bold text-[9px] px-3 flex items-center rounded-bl-lg uppercase tracking-wider">
                Most Popular
              </div>
              <div className="space-y-6">
                <div className="flex items-center gap-1.5">
                  <Sparkles className="h-5 w-5 text-primary fill-current" />
                  <h3 className="font-heading text-lg font-bold text-text-1">Pro Access</h3>
                </div>
                <p className="text-text-2 text-xs mt-1">Unlock the full power of adaptive, offline AI learning.</p>
                <div className="flex items-baseline">
                  <span className="font-heading text-3xl font-extrabold text-text-1">
                    {billingPeriod === 'monthly' ? '₦4,500' : '₦45,000'}
                  </span>
                  <span className="text-text-2 text-xs ml-1.5 font-semibold">
                    {billingPeriod === 'monthly' ? '/ month' : '/ year'}
                  </span>
                </div>
                <div className="w-full h-px bg-border/60" />
                <ul className="space-y-3.5 text-xs text-text-2">
                  <li className="flex items-center gap-2">
                    <Check className="h-4 w-4 text-primary shrink-0" strokeWidth={2.5} />
                    <span className="font-bold text-text-1">Everything in Free Tier</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <Check className="h-4 w-4 text-primary shrink-0" strokeWidth={2.5} />
                    <span className="font-semibold text-text-1">Unlimited Active Learning Goals</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <Check className="h-4 w-4 text-primary shrink-0" strokeWidth={2.5} />
                    <span>All 5 Cognitive Depths (from Lvl 1 to Expert)</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <Check className="h-4 w-4 text-primary shrink-0" strokeWidth={2.5} />
                    <span>Claude AI Explanations ("Confused?" Helper powered by Claude 3.5 Sonnet)</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <Check className="h-4 w-4 text-primary shrink-0" strokeWidth={2.5} />
                    <span className="font-semibold text-text-1">Full PWA Offline Downloads Shelf</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <Check className="h-4 w-4 text-primary shrink-0" strokeWidth={2.5} />
                    <span>Monaco Code Playground & AI Writing Workspaces</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <Check className="h-4 w-4 text-primary shrink-0" strokeWidth={2.5} />
                    <span>Milestone Badge Certificates Download</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <Check className="h-4 w-4 text-primary shrink-0" strokeWidth={2.5} />
                    <span>AI Coach Insights Trajectory & Study Vitals</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <Check className="h-4 w-4 text-primary shrink-0" strokeWidth={2.5} />
                    <span>Streak Activity Calendar Heatmap</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <Check className="h-4 w-4 text-primary shrink-0" strokeWidth={2.5} />
                    <span>Animated Mascot Interactivity</span>
                  </li>
                </ul>
              </div>
              <Link href="/signup" className="w-full">
                <button className="w-full py-3 bg-primary hover:bg-primary/95 text-white font-bold rounded-lg text-xs transition duration-150 cursor-pointer shadow-[0_0_12px_rgba(91,142,255,0.25)] hover:scale-[1.02] active:scale-[0.98]">
                  Start 7-Day Free Trial
                </button>
              </Link>
            </div>
          </div>
        </section>

        {/* FAQ SECTION */}
        <section id="faq" className="space-y-12 py-20 md:py-28 scroll-mt-24">
          <div className="text-center space-y-3">
            <span className="text-xs font-mono uppercase text-primary font-bold tracking-wider">Got Questions?</span>
            <h2 className="font-heading text-3xl font-extrabold text-text-1">Frequently Asked Questions</h2>
          </div>

          <div className="max-w-3xl mx-auto space-y-4">
            {faqs.map((faq, idx) => {
              const isOpen = openFaq === idx
              return (
                <div
                  key={idx}
                  className="bg-surface border border-border rounded-[10px] transition-all duration-200"
                >
                  <button
                    onClick={() => setOpenFaq(isOpen ? null : idx)}
                    type="button"
                    className="w-full text-left p-5 flex items-center justify-between font-heading font-bold text-sm text-text-1 hover:text-primary transition-colors cursor-pointer"
                  >
                    <span>{faq.q}</span>
                    <HelpCircle className={`h-4 w-4 text-text-3 transition-transform ${isOpen ? 'rotate-180 text-primary' : ''}`} />
                  </button>
                  {isOpen && (
                    <div className="px-5 pb-5 pt-1 text-xs text-text-2 leading-relaxed border-t border-border/30">
                      {faq.a}
                    </div>
                  )}
                </div>
              )
            })}
          </div>
        </section>

        {/* BOTTOM CALL TO ACTION (CTA) PANEL */}
        <div className="pt-20 pb-10 md:pt-28 md:pb-14">
          <section className="relative overflow-hidden rounded-[16px] border border-border bg-surface p-8 md:p-12 text-center space-y-6 shadow-lg">
          <div className="absolute inset-0 bg-gradient-to-r from-primary/10 to-accent/10 pointer-events-none blur-3xl" />

          <div className="max-w-2xl mx-auto space-y-4 relative">
            <h2 className="font-heading text-3xl md:text-4xl font-extrabold text-text-1 tracking-tight leading-tight">
              Ready to claim your path?
            </h2>
            <p className="text-text-2 text-xs sm:text-sm leading-relaxed">
              Join thousands of self-driven learners who are building customized, adaptive roadmaps that compile around their minds.
            </p>
            <div className="pt-4">
              <Link
                href="/signup"
                className="inline-flex items-center justify-center h-12 px-8 rounded-lg font-bold text-sm bg-primary hover:bg-primary-hover text-white shadow-[0_0_20px_rgba(91,142,255,0.35)] transition-transform duration-150 hover:-translate-y-0.5"
              >
                <span>Initialize Your Operating System</span>
                <ArrowRight className="ml-2 h-4 w-4" strokeWidth={2.5} />
              </Link>
            </div>
          </div>
          </section>
        </div>

      </main>

      {/* Footer */}
      <footer className="max-w-6xl w-full mx-auto px-6 pt-10 pb-10 mt-10 flex flex-col sm:flex-row items-center justify-between gap-4 text-xs text-text-3 border-t border-border/40 relative z-10">
        <div>
          &copy; {new Date().getFullYear()} Cognara. Built for modern learning operating systems. All rights reserved.
        </div>
        <div className="flex items-center space-x-4">
          <Link href="/privacy-policy" className="hover:text-text-2 transition-colors">
            Privacy Policy
          </Link>
          <span>&bull;</span>
          <Link href="/terms-of-service" className="hover:text-text-2 transition-colors">
            Terms of Service
          </Link>
        </div>
      </footer>
    </div>
  )
}
