'use client'

import React, { useState } from 'react'
import { Sliders } from 'lucide-react'

const depthLabels = ["", "Like I'm 10", "Beginner", "Intermediate", "Advanced", "Expert"]

const subjects = [
  { id: 'tech', label: 'Tech & Code', concept: 'JavaScript Closures' },
  { id: 'business', label: 'Business & Marketing', concept: 'Customer Acquisition Cost (CAC)' },
  { id: 'creative', label: 'Creative Arts', concept: 'Color Theory in Design' }
] as const

const explanations = {
  tech: [
    "",
    "Think of a closure like a magic backpack that a function carries around. Whenever the function is born, it packs all the variables from the room it was created in. Even if the function travels to a completely new place, it can unzip its backpack and grab those variables anytime!",
    "In JavaScript, a closure is a feature where a nested inner function retains access to the variables of its parent function, even after the parent function has finished running. It's like a function remembering its home town.",
    "A closure is the combination of a function bundled together with references to its surrounding state (the lexical environment). Lexical scoping determines variable access based on the physical location of declarations in the source code.",
    "Closures are heap-allocated variable environments captured during lexical parsing. When a parent context is popped off the execution stack, its activation record references are preserved in memory because the returned inner function maintains an active scope chain pointer to them.",
    "At the compiler layer (V8/SpiderMonkey), closures bypass stack allocation. The parser scans for context escaping; if a nested function references an outer binding, V8 allocates that binding in a Heap Context object rather than the Stack. The closure holds a [[Scope]] property reference, preventing GC sweep passes."
  ],
  business: [
    "",
    "Think of CAC like buying tickets to invite friends to a birthday party. If you spend $10 on party invitations and 5 friends show up, inviting each friend cost you $2! That is what CAC is—how much money you spend to get one new customer.",
    "In business, Customer Acquisition Cost (CAC) is the total amount of money a company spends to win a new customer. This includes marketing fees, sales salaries, and ads, divided by the number of customers gained.",
    "Customer Acquisition Cost (CAC) measures the efficiency of sales and marketing operations. It is computed by dividing total acquisition expenses (marketing spend, sales overhead, salaries) by the total number of acquired customers over a specific period.",
    "CAC is a critical unit economics efficiency metric. To evaluate enterprise viability, CAC must be analyzed in relation to LTV (Customer Lifetime Value) using the LTV:CAC ratio. An optimal ratio is 3:1, indicating that the gross margin generated by a customer is triple the cost to acquire them, factoring in payback periods.",
    "Analytically, CAC optimization requires dissecting marginal acquisition cost curves across paid channels. CAC is modeled as: CAC = (Total Marketing Spend + Total Sales Overheads + Customer Success Onboarding Cost) / Total Gained Customers. Dynamic cohort analysis must adjust CAC based on organic virality loops (K-factor) and churn decay coefficients."
  ],
  creative: [
    "",
    "Colors are like friends—some look super happy together, and some fight! Color Theory is a set of secret rules that artists use to mix colors so they look beautiful on your eyes. It is like matching clothes for a party!",
    "Color Theory is a set of practical guidelines for mixing colors and creating visual combinations. It uses the Color Wheel to show how primary colors (red, blue, yellow) combine to create secondary and tertiary tones that feel good to look at.",
    "Color Theory comprises the principles governing color mixing and the visual effects of specific color combinations. Underpinned by the color wheel, designers utilize contrast schemes (analogous, complementary, triadic) to create visual harmony and manage visual weight in compositions.",
    "Color Theory maps color physics and psychological perception. It defines color spaces using Hue, Saturation, and Value (HSV). Designers exploit complementary contrasts to stimulate photoreceptor cells (rods and cones) in the retina, using contrasting temperatures (warm vs cool) to establish visual hierarchy.",
    "At the intersection of optics and human perception, Color Theory is governed by additive (RGB) and subtractive (CMYK) color mixing systems. Chromatic relationships are mapped onto the CIE 1931 color space chromaticity diagram, where relative luminance contrast ratios and simultaneous contrast effects are calculated to ensure accessible visual designs."
  ]
}

export function DepthSimulator() {
  const [activeSubject, setActiveSubject] = useState<'tech' | 'business' | 'creative'>('tech')
  const [activeDepth, setActiveDepth] = useState<number>(3)

  return (
    <div id="features" className="py-20 md:py-28 scroll-mt-24">
      <section className="bg-surface border border-border rounded-[12px] p-6 md:p-8 space-y-8 shadow-md relative overflow-hidden">
        <div className="absolute right-0 top-0 w-36 h-36 rounded-full bg-primary/5 blur-2xl pointer-events-none" />

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-center">
          <div className="lg:col-span-5 space-y-4">
            <div className="inline-flex items-center space-x-1.5 text-accent font-mono text-xs uppercase tracking-wider font-bold">
              <Sliders className="h-4 w-4" />
              <span>Feature Showcase</span>
            </div>
            <h3 className="font-heading text-2xl font-bold tracking-tight text-text-1 leading-tight">
              Adaptive Explanation Depth
            </h3>
            <p className="text-text-2 text-xs leading-relaxed">
              Watch how Cognara re-structures explanations across 5 distinct cognitive levels. Select a domain tab and click on the depths to see the explanation transform.
            </p>

            {/* Category tabs */}
            <div className="flex flex-col space-y-2 pt-2">
              <span className="text-[10px] font-mono text-text-3 uppercase tracking-wider">Select Domain</span>
              <div className="flex flex-col sm:flex-row gap-2">
                {subjects.map((sub) => (
                  <button
                    key={sub.id}
                    onClick={() => {
                      setActiveSubject(sub.id)
                      setActiveDepth(3) // reset depth to intermediate
                    }}
                    type="button"
                    className={`px-3 py-2 text-left rounded-md border text-xs font-semibold transition-all cursor-pointer ${activeSubject === sub.id
                      ? 'border-primary bg-primary/5 text-primary'
                      : 'border-border bg-surface-alt text-text-2 hover:text-text-1'
                      }`}
                  >
                    {sub.label}
                  </button>
                ))}
              </div>
            </div>
          </div>

          {/* Simulated UI window */}
          <div className="lg:col-span-7 space-y-4">
            {/* Depth Toggles Header */}
            <div className="flex flex-wrap gap-2 border-b border-border pb-3 justify-start">
              {[1, 2, 3, 4, 5].map((lvl) => (
                <button
                  key={lvl}
                  onClick={() => setActiveDepth(lvl)}
                  type="button"
                  className={`px-3 py-1.5 rounded-sm font-mono text-[10px] uppercase font-bold tracking-wide transition-all cursor-pointer ${activeDepth === lvl
                    ? 'bg-primary text-white shadow-[0_0_12px_rgba(91,142,255,0.25)]'
                    : 'bg-surface-alt border border-border text-text-2 hover:text-text-1'
                    }`}
                >
                  <span>Lvl {lvl}</span>
                </button>
              ))}
            </div>

            {/* Display Box */}
            <div className="p-5 bg-surface-alt border border-border/80 rounded-[8px] space-y-3 min-h-[160px] flex flex-col justify-between border-l-2 border-l-accent">
              {/* Header Row with Heading and Badge */}
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 border-b border-border/30 pb-2">
                <h4 className="font-heading text-sm font-bold text-text-1">
                  Concept: {subjects.find(s => s.id === activeSubject)?.concept}
                </h4>
                <div className="opacity-75">
                  <span className="inline-flex items-center px-1.5 py-0.5 border border-accent/20 bg-accent/5 text-accent text-[8px] font-mono font-bold uppercase rounded-sm">
                    GENERATED — Lvl {activeDepth} ({depthLabels[activeDepth]})
                  </span>
                </div>
              </div>
              <p className="text-text-2 text-xs leading-relaxed whitespace-pre-line pr-2 flex-1">
                {explanations[activeSubject][activeDepth]}
              </p>
            </div>
          </div>
        </div>
      </section>
    </div>
  )
}
